### ISSUE TITLE
Sanchez-Lengeling et al., "Machine Learning for Scent: Learning Generalizable Perceptual Representations of Small Molecules"

### ISSUE THREAD

**Issue by SimonEnsemble** [pyrfume/pyrfume-data#174]
Sanchez-Lengeling et al. [here](https://arxiv.org/pdf/1910.10685.pdf) combine GoodScents and Leffingwell PMP 2001 then process it. was wondering if it would be possible to add their combined data set for benchmarking with their results. thanks!

<img width="704" alt="Screen Shot 2022-09-15 at 8 47 09 PM" src="https://user-images.githubusercontent.com/30643894/190552478-2878266c-fc69-4595-8694-b131d25ef2a0.png">

**Comment by rgerkin** [comment]
The combined dataset has not been published and is not otherwise available.  But both source materials can be found in pyrfume-data; the pyrfume-data/leffingwell dataset comes directly from the Zenodo version contributed by the authors of the paper above.  The pyrfume-data/goodscents dataset was contributed by a third party in a PR, and won't match what was used in the paper, but might be useful as a coarse approximation.

**Comment by SimonEnsemble** [comment]
thanks.
surprising the data from the folks at Google Research are not available...
they have a follow-up study [here](https://www.biorxiv.org/content/10.1101/2022.09.01.504602v2.abstract)---hope this data set will be available...
![image](https://user-images.githubusercontent.com/30643894/190692255-6bacd04f-cf0e-40a1-a47d-0d1ae68f4b9d.png)
