### ISSUE TITLE
nat_geo_1986 NGS.csv link

### ISSUE THREAD

**Issue by joelmainland** [pyrfume/pyrfume-data#93]
The NGS.csv looks like it links to the large file system--not sure how to load it with load_data, as I just get the three-line file.

**Comment by rgerkin** [comment]
It's a token describing the location of the real file.  This is going to take some work to fix the right way (because pyrfume and rfume will need to get user-associated API tokens to git-lfs).  We can fix this the fast way by hosting these files elsewhere, and adding a check that, after loading the .csv file, looks to see if it is this kind of "link" file, and then follows it to get the real data.  Bob would have to implement this in parallel.  Another option is to break this into about 30 chunks (behavior_1, behavior_2, etc.) so each one could be downloaded directly from GitHub in sequence and then concatenated.

**Comment by rgerkin** [comment]
Currently loads with pyrfume; rfume will need to implement the same logic to load it.  Have @KingFunk contact me if interested.
